name: CI

on: [push]

jobs:
  build_components:
    name: Build Components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Install NPM Deps
        run: yarn install
      - name: Build 
        run: yarn --cwd ./tuscany-components build
      - name: Upload Build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./tuscany-components/build

  deploy_components:
    name: Deploy Components
    needs: build_components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Restore Build Dir
        uses: actions/download-artifact@v1
        with:
          name: build
      - name: Add Vercel Config
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_COMPONENTS_PROJECT_ID: ${{ secrets.VERCEL_COMPONENTS_PROJECT_ID }}
        run: |
          mkdir -p ./tuscany-components/build/.vercel
          printf '{ "orgId": "%s", "projectId", "%s" }' \
            $VERCEL_ORG_ID \
            $VERCEL_COMPONENTS_PROJECT_ID \
            > ./tuscany-components/build/.vercel/project.json
      - name: Deploy Build
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: yarn --cwd ./tuscany-components deploy
