name: CI

on: [push]

jobs:
  build_components:
    name: Build Components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '14'
      - name: Yarn install
        run: |
          yarn --cwd ./tuscany-components install --focus
          yarn --cwd ./tuscany-components build
      - name: Upload build
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ./tuscany-components/build
