name: Prepare Integration Candidate

# on:
#   pull_request:
#     branches:
#       - develop

on:
  push:
    branches:
      feature/*

jobs:
  establish_changed:
    name: Establish changed packages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Run Lerna changed
        run: |
          npx lerna changed --all --json | \
          npx jq 'map(.name)' > \
          changed.json
      - name: Upload changed.json
        uses: actions/upload-artifact@v1
        with:
          name: changed
          path: ./changed.json

  publish_packages_to_npm:
    name: Publish packages to NPM
    needs: establish_changed
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Set up NPM auth
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm config set \
            '//registry.npmjs.org/:_authToken' \
            "${NPM_TOKEN}"
      - name: Set up Git
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name 'Jake Elder'
          git config user.email 'jake@jakes.world'
          git config user.password ${GITHUB_TOKEN}
      - name: Version
        run: |
          npx lerna version \
            --conventional-commits \
            --conventional-prerelease \
            --preid ic \
            --exact \
            --ignore-changes '**/*.md' \
            --yes
      - name: Publish
        run: npx lerna publish from-package --yes

  # deploy_storybook:
  #   name: Deploy Storybook
  #   runs-on: ubuntu-latest

  # deploy_strapi:
  #   name: Deploy Strapi
  #   runs-on: ubuntu-latest

  # deploy_front_end:
  #   name: Deploy front end
  #   runs-on: ubuntu-latest
